# fly.toml app configuration file generated for quiz-app-backend-jp on 2025-04-14T22:04:47+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "quiz-app-backend-jp"
primary_region = "nrt"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[mounts]
  source = "quiz_data"
  destination = "/data"
