# fly.toml app configuration file generated for quiz-app-backend-jp on 2025-04-14T22:04:47+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "quiz-app-backend-jp"
primary_region = "nrt"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = false  #  Changed from true to keep machines going rather than having slow start up in classes
  auto_start_machines = true  #  Updated at 14:20 JST, July 23, 2025
  min_machines_running = 1   #  Changed from 0 to keep one machine going, to hopefully have app start faster

[mounts]
  source = "quiz_data"
  destination = "/data"
